Repository kyma-project/examples, pull requests merged in 2018-10, with the labels that each got.

#8 Enable automated deployment of examples
  Jenkinsfile
  event-email-service/Jenkinsfile
  event-email-service/README.md
  event-subscription/lambda/README.md
  event-subscription/lambda/deployment/sample-publisher.yaml
  examples-chart/templates/deployments/event-email-service/Pod.yaml
  examples-chart/templates/deployments/http-db-service/Pod.yaml
  examples-chart/values.yaml
  http-db-service/Jenkinsfile
  http-db-service/README.md
  orchestrator.Jenkinsfile
Labels: area/examples

#42 Update examples EventActivation & Subscription CRDs to latest specs
  event-subscription/lambda/README.md
  event-subscription/lambda/deployment/event-activation.yaml
  event-subscription/lambda/deployment/subscription.yaml
  event-subscription/service/README.md
  event-subscription/service/example-event-activation.yaml
  event-subscription/service/example-subscriber.yaml
  event-subscription/service/example-subscription.yaml
  examples-chart/templates/deployments/pre-install-rbac.yaml
Labels: area/eventing, area/examples, area/serverless

#46 Update golang buildpack version and disable Whitesource
  call-ec/Jenkinsfile
  event-email-service/Jenkinsfile
  http-db-service/Jenkinsfile
  monitoring-custom-metrics/Jenkinsfile
  tests/http-db-service/Jenkinsfile
Labels: area/ci

#45 Add example for tracing configuration
  README.md
  example-tracing/.gitignore
  example-tracing/Dockerfile
  example-tracing/Gopkg.lock
  example-tracing/Gopkg.toml
  example-tracing/Jenkinsfile
  example-tracing/README.md
  example-tracing/build.sh
  example-tracing/example-tracing.yaml
  example-tracing/order-front.go
  orchestrator.Jenkinsfile
Labels: area/documentation, area/examples, area/tracing

#43 Enable external links validation on PRs
  governance.Jenkinsfile
Labels: area/ci, area/documentation, enhancement

#50 Add aerfio for CODEOWNERS
  CODEOWNERS
Labels: area/community

#51 Add user key to whitesource configuration
  event-email-service/Jenkinsfile
Labels: area/ci

#52 Copy template for security issues
  .github/ISSUE_TEMPLATE/security-vulnerability.md
Labels: area/documentation, area/security, enhancement, sig/core

#53 Disable external links validation on master
  governance.Jenkinsfile
  orchestrator.Jenkinsfile
Labels: area/ci, area/community, enhancement, priority/critical
