Repository kyma-project/examples, pull requests merged in 2018-11, with the labels that each got.

#59 Enable automated testing for examples
  Jenkinsfile
  event-email-service/Jenkinsfile
  event-email-service/deployment/deployment.yaml
  event-subscription/lambda/deployment/sample-publisher.yaml
  event-subscription/lambda/deployment/subscription.yaml
  event-subscription/service/example-publisher.yaml
  examples-chart/README.md
  examples-chart/templates/deployments/event-email-service/Pod.yaml
  examples-chart/templates/deployments/event-subscription/lambda/Pod.yaml
  examples-chart/templates/deployments/pre-install-rbac.yaml
  examples-chart/templates/tests/event-email-service/Pod.yaml
  examples-chart/templates/tests/event-subscription/lambda/Pod.yaml
  examples-chart/templates/tests/http-db-service/Pod.yaml
  examples-chart/values.yaml
  gateway/service/deployment.yaml
  http-db-service/deployment/deployment.yaml
  tests/http-db-service/Jenkinsfile
  tests/http-db-service/deployment/pod.yaml
Labels: area/ci, area/examples

#61 Fix logic for test clean up
  Jenkinsfile
Labels: area/ci, area/examples

#60 Add the note and minor corrections in the main README.md document
  README.md
  call-ec/README.md
  call-ec/diagram.png
  call-ec/diagram.svg
  call-ec/diagram.xml
  event-email-service/README.md
  event-subscription/lambda/README.md
  event-subscription/service/README.md
  example-tracing/README.md
  examples-chart/README.md
  gateway/README.md
  http-db-service/README.md
  monitoring-alert-rules/README.md
  monitoring-custom-metrics/README.md
  service-binding/lambda/README.md
  tests/README.md
Labels: area/documentation

#63 Add test for service binding lambda example
  Jenkinsfile
  examples-chart/templates/deployments/pre-install-rbac.yaml
  examples-chart/templates/deployments/service-binding/lambda/Pod.yaml
  examples-chart/templates/tests/event-subscription/lambda/Pod.yaml
  examples-chart/templates/tests/service-binding/lambda/Pod.yaml
  examples-chart/values.yaml
  orchestrator.Jenkinsfile
  service-binding/lambda/deployment/lambda-function.yaml
Labels: area/examples

#65 Increase resource quota for a namespace
  Jenkinsfile
  examples-chart/templates/tests/service-binding/lambda/Pod.yaml
  resourceQuota.yaml
Labels: area/examples

#64 Refactor tracing example
  README.md
  example-tracing/README.md
  orchestrator.Jenkinsfile
  tracing/.gitignore
  tracing/Dockerfile
  tracing/Gopkg.lock
  tracing/Gopkg.toml
  tracing/Jenkinsfile
  tracing/README.md
  tracing/build.sh
  tracing/deployment/deployment.yaml
  tracing/src/order-front.go
Labels: area/documentation

#75 Migrate examples to Prow
  call-ec/.eslinterrc
  call-ec/Jenkinsfile
  call-ec/Makefile
  event-email-service/.eslinterrc
  event-email-service/Jenkinsfile
  event-email-service/Makefile
  event-email-service/make.sh
  http-db-service/Jenkinsfile
  http-db-service/Makefile
  http-db-service/make.sh
  monitoring-custom-metrics/Gopkg.lock
  monitoring-custom-metrics/Gopkg.toml
  monitoring-custom-metrics/Makefile
  monitoring-custom-metrics/make.sh
  tests/http-db-service/Gopkg.lock
  tests/http-db-service/Gopkg.toml
  tests/http-db-service/Makefile
  tests/http-db-service/make.sh
  tracing/Gopkg.lock
  tracing/Gopkg.toml
  tracing/Jenkinsfile
  tracing/Makefile
Labels: area/ci
