Repository kyma-project/examples, pull requests merged in 2018-12, with the labels that each got.

#78 use short host names in api resources
  call-ec/README.md
  call-ec/expose-ec-function.yaml
  call-ec/web-ui/deployment.yaml
  gateway/lambda/api-with-auth.yaml
  gateway/lambda/api-with-default-auth.yaml
  gateway/lambda/api-without-auth.yaml
  gateway/service/api-with-auth.yaml
  gateway/service/api-with-default-auth.yaml
  gateway/service/api-without-auth.yaml
  tracing/README.md
  tracing/deployment/deployment.yaml
Labels: area/documentation

#80 Update stale.yml with new stale label
  .github/stale.yml
Labels: area/community

#84 Update the link
  README.md
Labels: area/documentation

#79 Fix Subscription domain
  event-subscription/lambda/deployment/subscription.yaml
  event-subscription/service/example-subscription.yaml
  examples-chart/templates/deployments/pre-install-rbac.yaml
Labels: area/eventing

#85 Adjust BUC CRs domain to kyma-project.io
  examples-chart/templates/deployments/pre-install-rbac.yaml
  service-binding/lambda/deployment/lambda-function.yaml
  service-binding/service/deployment/http-db-service.yaml
Labels: enhancement
