Repository kyma-project/examples, pull requests merged in 2019-01, with the labels that each got.

#86 Remove Jenkins configurations
  CODEOWNERS
  Jenkinsfile
  call-ec/Jenkinsfile
  event-email-service/Jenkinsfile
  governance.Jenkinsfile
  http-db-service/Jenkinsfile
  monitoring-custom-metrics/Jenkinsfile
  orchestrator.Jenkinsfile
  tests/http-db-service/Jenkinsfile
  tracing/Jenkinsfile
Labels: area/ci

#88 Remove the invalid CI information
  CONTRIBUTING.md
Labels: area/documentation

#93 Fix broken link
  event-subscription/service/README.md
Labels: area/documentation

#96 Add app label for tracing
  event-email-service/deployment/deployment.yaml
  gateway/service/deployment.yaml
  http-db-service/Makefile
  http-db-service/deployment/deployment.yaml
  tests/http-db-service/deployment/pod.yaml
Labels: area/tracing
