Repository kyma-project/examples, pull requests merged in 2019-07, with the labels that each got.

#140 Update stale bot settings to exclude epics
  .github/stale.yml
Labels: area/community

#141 Generate random temperature
  monitoring-custom-metrics/main.go
Labels: area/examples, enhancement

#139 Change eventing publish urls to the new ones
  event-subscription/lambda/README.md
  event-subscription/service/README.md
  examples-chart/templates/tests/event-subscription/lambda/Pod.yaml
Labels: area/eventing

#142 Bump Custom Metrics example
  monitoring-custom-metrics/deployment/deployment.yaml
Labels: area/examples
