Repository kyma-project/examples, pull requests merged in 2019-04, with the labels that each got.

#105 Update CODEOWNERS
  CODEOWNERS
Labels: area/community, enhancement

#106 Various fixes for kyma-examples
  event-subscription/lambda/README.md
  http-db-service/Gopkg.lock
  http-db-service/README.md
  monitoring-alert-rules/README.md
  monitoring-custom-metrics/README.md
  service-binding/lambda/README.md
Labels: area/examples

#112 Fix gateway example
  gateway/README.md
Labels: area/documentation, area/service-mesh, bug
