Repository kyma-project/examples, pull requests merged in 2022-09, with the labels that each got.

#205 Scale with keda
  CODEOWNERS
  scale-to-zero-with-keda/README.md
  scale-to-zero-with-keda/assets/scaling-scenario.drawio
  scale-to-zero-with-keda/assets/scaling-scenario.png
  scale-to-zero-with-keda/k8s-resources/http-proxy-fn.yml
  scale-to-zero-with-keda/k8s-resources/scalable-worker-fn.yml
  scale-to-zero-with-keda/src/http-proxy-fn/handler.js
  scale-to-zero-with-keda/src/http-proxy-fn/package.json
  scale-to-zero-with-keda/src/scalable-worker-fn/handler.js
  scale-to-zero-with-keda/src/scalable-worker-fn/package.json
Labels: size/L, lgtm

#208 Upgrade sample function to v1alpha2
  incluster_eventing/Makefile
  incluster_eventing/k8s-resources/emitter-fn.yaml
  incluster_eventing/k8s-resources/receiver-fn.yaml
  incluster_eventing/src/render-manifests.sh
Labels: size/M, lgtm

#209 fix broken link in examples repo
  gateway/README.md
Labels: size/XS, lgtm

#207 tutorial for kiali
  kiali/README.md
  kiali/values.yaml
Labels: size/L, lgtm
