Repository kyma-project/examples, pull requests merged in 2022-10, with the labels that each got.

#210 Enhance Kiali example
  README.md
  kiali/README.md
  kiali/apirule.yaml
Labels: size/M, lgtm

#213 Loki tutorial
  loki/README.md
  loki/grafana-values.yaml
  loki/logpipeline-custom.yaml
  loki/loki-values.yaml
Labels: size/L, lgtm

#215 Update codeowners
  CODEOWNERS
Labels: size/XS, lgtm

#214 Otel tracing demo
  trace-demo/README.md
  trace-demo/istio-values.yaml
  trace-demo/tracepipeline.yaml
  trace-demo/values.yaml
Labels: area/tracing, size/L, lgtm

#216 improvments to loki tutorial
  loki/README.md
  loki/logpipeline.yaml
Labels: size/S, lgtm
