Repository kyma-project/examples, pull requests merged in 2022-11, with the labels that each got.

#206 First version on how to bring your custom kube-prometheus-stack
  CODEOWNERS
  monitoring-custom-metrics/README.md
  monitoring-custom-metrics/deployment/deployment.yaml
  prometheus/README.md
  prometheus/istio/configmap-istio-grafana-dashboards.yaml
  prometheus/istio/configmap-istio-services-grafana-dashboards.yaml
  prometheus/istio/podmonitor-istio-proxy.yaml
  prometheus/istio/servicemonitor-istiod.yaml
  prometheus/values.yaml
Labels: area/documentation, area/monitoring, size/XXL, lgtm

#220 updated to newest chart version and removed avoidable overrides
  trace-demo/README.md
  trace-demo/values.yaml
Labels: size/L, lgtm

#219 Exposing the deployed Grafana in the Loki tutorial
  loki/README.md
  loki/apirule.yaml
  loki/dashboard-configmap.yaml
Labels: size/M, lgtm

#221 fixed broken link in loki tutorial
  loki/README.md
Labels: size/XS, lgtm

#223 remove Maja from codeowners
  CODEOWNERS
Labels: size/XS, lgtm
