Repository kyma-project/examples, pull requests merged in 2022-01, with the labels that each got.

#189 Add Grzegorz as a documentation CODEOWNER in Examples
  CODEOWNERS
Labels: area/community, size/XS, approved, lgtm

#191 fix broken kubeless link
  service-binding/lambda/README.md
Labels: size/XS, lgtm

#188 Incluster eventing
  incluster_eventing/README.md
  incluster_eventing/emitter/config.yaml
  incluster_eventing/emitter/handler.js
  incluster_eventing/emitter/package.json
  incluster_eventing/receiver/config.yaml
  incluster_eventing/receiver/handler.js
  incluster_eventing/receiver/package.json
Labels: size/M, lgtm
