Repository kyma-project/examples, pull requests merged in 2022-12, with the labels that each got.

#225 Adapt service names in the trace demo
  trace-demo/README.md
  trace-demo/istio-values.yaml
  trace-demo/values.yaml
Labels: size/M, lgtm

#224 Move Prometheus custom metrics and alerting tutorials
  CODEOWNERS
  README.md
  prometheus/README.md
  prometheus/monitoring-alert-rules/README.md
  prometheus/monitoring-alert-rules/deployment/alert-rule.yaml
  prometheus/monitoring-custom-metrics/Dockerfile
  prometheus/monitoring-custom-metrics/Gopkg.lock
  prometheus/monitoring-custom-metrics/Gopkg.toml
  prometheus/monitoring-custom-metrics/Makefile
  prometheus/monitoring-custom-metrics/README.md
  prometheus/monitoring-custom-metrics/deployment/deployment.yaml
  prometheus/monitoring-custom-metrics/deployment/service-monitor.yaml
  prometheus/monitoring-custom-metrics/go.mod
  prometheus/monitoring-custom-metrics/go.sum
  prometheus/monitoring-custom-metrics/main.go
  prometheus/monitoring-grafana-dashboard/README.md
Labels: size/L, lgtm

#218 Sync kubeless.py
  custom-serverless-runtime-image/Dockerfile
  custom-serverless-runtime-image/kubeless/ce.py
  custom-serverless-runtime-image/kubeless/kubeless.py
  custom-serverless-runtime-image/kubeless/requirements.txt
  custom-serverless-runtime-image/kubeless/tracing.py
Labels: size/L, lgtm

#226 Replace missing links in Prometheus example by raw files
  prometheus/monitoring-custom-metrics/README.md
Labels: size/XS, lgtm

#227 Add instructions to set up alerting channels to Prometheus example
  prometheus/README.md
  prometheus/alertmanager-values.yaml
  prometheus/values.yaml
Labels: size/M, lgtm

#222 Reflect changes in cloudevents api
  incluster_eventing/src/emitter-fn/config.yaml
  incluster_eventing/src/emitter-fn/handler.js
  incluster_eventing/src/emitter-fn/package.json
  incluster_eventing/src/receiver-fn/config.yaml
Labels: size/S, lgtm

#228 refined scraping by annotation in prometheus tutorial
  prometheus/README.md
  prometheus/values.yaml
Labels: size/M, lgtm

#229 Add nataliasitko to codeowners
  CODEOWNERS
Labels: size/XS, lgtm

#231 broken link fix
  orders-service/README.md
Labels: size/XS, lgtm
