Repository kyma-project/examples, pull requests merged in 2022-04, with the labels that each got.

#197 Fix the broken link to the README.md template
  CONTRIBUTING.md
Labels: kind/bug, area/documentation, size/XS, lgtm

#199 Use alpine to exec sh in e2e tests
  orders-service/Dockerfile
Labels: size/XS, lgtm

#200 Readible storeage type for additional test assertions
  orders-service/internal/handler/order_handler.go
  orders-service/internal/service/order_service.go
  orders-service/internal/store/memory_store.go
  orders-service/internal/store/redis_store.go
  orders-service/internal/store/store.go
Labels: size/S, lgtm

#198 Add `custom-runtime` example
  README.md
  custom-serverless-runtime-image/Dockerfile
  custom-serverless-runtime-image/README.md
  custom-serverless-runtime-image/kubeless/kubeless.py
  custom-serverless-runtime-image/kubeless/requirements.txt
Labels: area/serverless, size/L, lgtm
