Repository kyma-project/examples, pull requests merged in 2023-02, with the labels that each got.

#235 fix link to browser instrumentation
  trace-demo/README.md
Labels: size/XS, lgtm

#237 fix cni problems in prometheus example
  prometheus/values.yaml
Labels: do-not-merge/hold, size/XS, lgtm

#236 added new tutorial for metrics ingestion based on otel-collector
  CODEOWNERS
  metrics-otlp/README.md
  metrics-otlp/assets/overview.drawio.svg
  metrics-otlp/metrics-agent-values.yaml
  metrics-otlp/metrics-gateway-values.yaml
  metrics-otlp/secret-values.yaml
Labels: size/XXL, lgtm
