Repository kyma-project/examples, pull requests merged in 2023-10, with the labels that each got.

#272 Add default persistence settings to prometheus example
  kiali/README.md
  prometheus/README.md
  prometheus/values.yaml
Labels: size/M, lgtm

#273 update custom-metrics to newest image version
  prometheus/monitoring-custom-metrics/deployment/deployment.yaml
Labels: size/XS, lgtm

#274 Fix scale to zero example
  scale-to-zero-with-keda/README.md
  scale-to-zero-with-keda/k8s-resources/http-proxy-fn.yml
  scale-to-zero-with-keda/k8s-resources/scalable-worker-fn.yml
  scale-to-zero-with-keda/src/http-proxy-fn/handler.js
  scale-to-zero-with-keda/src/http-proxy-fn/package.json
Labels: size/M, lgtm

#275 unified namespace variable naming
  event-email-service/README.md
  gateway/README.md
  http-db-service/README.md
  jaeger/README.md
  kiali/README.md
  loki/README.md
  metrics-otlp/README.md
  metrics-otlp/metrics-agent-values.yaml
  prometheus/README.md
  prometheus/monitoring-alert-rules/README.md
  prometheus/monitoring-custom-metrics/README.md
  prometheus/monitoring-grafana-dashboard/README.md
  service-binding/lambda/README.md
  service-binding/service/README.md
  trace-demo/README.md
  tracing/README.md
Labels: size/L, lgtm
