Repository kyma-project/examples, pull requests merged in 2023-07, with the labels that each got.

#246 Adjust observability examples
  jaeger/README.md
  kiali/README.md
  loki/README.md
Labels: area/tracing, area/logging, size/S, lgtm, kind/cleanup

#247 fix broken links
  incluster_eventing/README.md
  trace-demo/README.md
Labels: size/XS, lgtm

#249 update of otel-collector in metrics example
  metrics-otlp/README.md
  metrics-otlp/metrics-agent-values.yaml
Labels: size/S, lgtm

#250 version update for otel-demo example
  trace-demo/README.md
  trace-demo/values.yaml
Labels: size/M, lgtm

#252 adjust OTEL demo to have proper protocols defined in the used k8s services
  trace-demo/values.yaml
Labels: size/M, lgtm

#251 Extend the sample app with a Histogram and a Summary
  prometheus/monitoring-custom-metrics/.gitignore
  prometheus/monitoring-custom-metrics/Dockerfile
  prometheus/monitoring-custom-metrics/main.go
Labels: size/M, lgtm

#253 Add custom metric image build-n-publish workflow
  .github/workflows/cutom-metrics-docker-image.yaml
Labels: size/M, lgtm
