Repository kyma-project/examples, pull requests merged in 2023-12, with the labels that each got.

#278 docs: Remove 3 telemetry examples
  README.md
  jaeger/README.md
  jaeger/values.yaml
  loki/README.md
  loki/apirule.yaml
  loki/dashboard-configmap.yaml
  loki/grafana-values.yaml
  loki/loki-values.yaml
  loki/promtail-values.yaml
  trace-demo/README.md
  trace-demo/values.yaml
  tracing/README.md
Labels: area/documentation, size/XL, lgtm, area/telemetry, cla: yes

#280 Add preriquisite to have Istio enabled in Prometheus example
  prometheus/prometheus.md
Labels: size/XS, lgtm, cla: yes

#281 Remove the Prometheus scaler example
  scale-to-zero-with-keda/README.md
  scale-to-zero-with-keda/assets/scaling-scenario.drawio
  scale-to-zero-with-keda/assets/scaling-scenario.png
  scale-to-zero-with-keda/k8s-resources/http-proxy-fn.yml
  scale-to-zero-with-keda/k8s-resources/peer-authentication.yaml
  scale-to-zero-with-keda/k8s-resources/scalable-worker-fn.yml
  scale-to-zero-with-keda/src/http-proxy-fn/handler.js
  scale-to-zero-with-keda/src/http-proxy-fn/package.json
  scale-to-zero-with-keda/src/scalable-worker-fn/handler.js
  scale-to-zero-with-keda/src/scalable-worker-fn/package.json
Labels: size/L, lgtm, cla: yes

#282 fix: Allow createSecret job to create secrets when istio is enabled
  prometheus/values.yaml
Labels: size/XS, lgtm, cla: yes
