Repository kyma-project/examples, pull requests merged in 2023-06, with the labels that each got.

#243 Update to official loki chart and switched to static label map for loki integration
  loki/README.md
  loki/apirule.yaml
  loki/grafana-values.yaml
  loki/logpipeline.yaml
  loki/loki-values.yaml
  loki/promtail-values.yaml
Labels: size/L, lgtm

#244 fixed namespace in otel-demo example
  trace-demo/README.md
Labels: size/XS, lgtm

#245 Adjust keda example to latest kyma changes
  CODEOWNERS
  scale-to-zero-with-keda/README.md
  scale-to-zero-with-keda/k8s-resources/http-proxy-fn.yml
  scale-to-zero-with-keda/k8s-resources/scalable-worker-fn.yml
Labels: area/documentation, area/serverless, size/M, lgtm
