Repository kyma-project/examples, pull requests merged in 2023-09, with the labels that each got.

#267 chore: Remove not used github action (build docker image for metric producer)
  .github/workflows/custom-metrics-docker-image.yaml
Labels: size/M, lgtm, kind/chore

#268 switch link checking to GH action
  .github/workflows/markdown-link-check.yml
  CODEOWNERS
  custom-serverless-runtime-image/README.md
  jaeger/README.md
  kiali/README.md
  loki/README.md
  milv.config.yaml
  prometheus/monitoring-custom-metrics/README.md
  trace-demo/README.md
Labels: size/M, lgtm

#269 Fix map parsing error in Kiali example values
  kiali/values.yaml
Labels: size/XS, lgtm

#270 update to otel-demo 0.24.0
  trace-demo/README.md
  trace-demo/values.yaml
Labels: size/M, lgtm

#271 Add Telemetry module as a prerequisite for observability examples
  jaeger/README.md
  loki/README.md
  trace-demo/README.md
Labels: size/XS, lgtm, area/telemetry, kind/chore
