Repository kyma-project/examples, pull requests merged in 2024-03, with the labels that each got.

#283 Bump event-email-service dependencies
  event-email-service/package-lock.json
  event-email-service/package.json
Labels: size/XXL, lgtm, cla: yes

#284 Bump dependencies
  custom-serverless-runtime-image/kubeless/requirements.txt
  orders-service/function/package.json
Labels: size/XS, lgtm, cla: yes

#286 Remove Serverless examples
  README.md
  custom-serverless-runtime-image/Dockerfile
  custom-serverless-runtime-image/README.md
  custom-serverless-runtime-image/kubeless/ce.py
  custom-serverless-runtime-image/kubeless/kubeless.py
  custom-serverless-runtime-image/kubeless/requirements.txt
  custom-serverless-runtime-image/kubeless/tracing.py
  incluster_eventing/.github/workflows/deploy.yml
  incluster_eventing/Makefile
  incluster_eventing/README.md
  incluster_eventing/k8s-resources/emitter-fn.yaml
  incluster_eventing/k8s-resources/receiver-fn.yaml
  incluster_eventing/src/emitter-fn/config.yaml
  incluster_eventing/src/emitter-fn/handler.js
  incluster_eventing/src/emitter-fn/package.json
  incluster_eventing/src/receiver-fn/config.yaml
  incluster_eventing/src/receiver-fn/handler.js
  incluster_eventing/src/receiver-fn/package.json
  orders-service/function/handler.js
  orders-service/function/package.json
Labels: area/documentation, area/serverless, size/XL, lgtm, cla: yes
